### ISSUE TITLE
Unify evaluation time and build time item operations

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#1124]
Right now evaluation time and build time item operations support different operations and behave differently. It would be nice to unify them, so users have the same experience when using both types of items.

- [ ] [Add Update attribute for dynamic item tags](https://github.com/Microsoft/msbuild/issues/889)
- [ ] [static Update should support dynamic Update's feature of not having any attributes](https://github.com/Microsoft/msbuild/issues/955)
- [ ] [Migrate keepmetadata and removemetadata to valid evaluation time item operations](https://github.com/Microsoft/msbuild/issues/1123)
- [ ] [Migrate build time item operations to use the same matching code as eval time operations](https://github.com/Microsoft/msbuild/issues/1122)

**Comment by cdmihai** [comment]
Please update description with other differences, if any.

**Comment by Nirmal4G** [comment]
Really want this happen. It's painful, especially for the beginners to have to know the differences!!!
