### ISSUE TITLE
AssemblyLoadContext-related task errors in 16.5

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#5202]
## Background

Before 3.1.200, MSBuild tasks and their dependencies were loaded into the default ALC. Since an ALC can have only one assembly loaded for the same name (not including version), this forced all tasks to use the same version of dependencies, and that version had to match the one delivered in the .NET Core SDK (if the assembly was there). This was very annoying and broke people.

In MSBuild 16.5/SDK 3.1.200, we isolated plugins in their own ALC (microsoft/msbuild#4916). We planned to extend this in the .NET 5 timeframe to use an AssemblyDependencyResolver, to further improve the situation for native dependencies (microsoft/msbuild#5037).

There is an environment-variable-based workaround `MSBUILDSINGLELOADCONTEXT=1` available to revert to the previous behavior.

## Problems

This change broke some tasks that use reflection or fancy assembly loading inside the task implementation. All users of affected tasks are broken, not just the maintainers of the tasks.

Known failures are:

•	GitVersionTask (457 NuGet downloads/day)
•	Fody <6.0.4 (2730 downloads/day, but I don’t know the version breakdown)
•	SpecFlow (3215 downloads/day)
•	MSBump (92 downloads/day, repo archived)

## Related issues

- [x] https://github.com/dotnet/sdk/issues/10878
- [x] https://github.com/SpecFlowOSS/SpecFlow/issues/1912
- [x] GitTools/GitVersion#2063 (fixed in upcoming 5.3.0)
- [x] Fody https://github.com/dotnet/sdk/issues/10878#issuecomment-609395898 (fixed in 6.0.4+)
- [ ] MSBump https://github.com/dotnet/core/issues/4404#issuecomment-605962124
- [x] coverlet.msbuild 2.6.3, resolved in at least 2.8.1 (reported https://github.com/dotnet/sdk/issues/11274) possibly fixed by https://github.com/tonerdo/coverlet/pull/625
- [x] microsoft.web.librarymanager.build 1.0.163 ([AB#1093418](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1093418)). No repro in latest 2.1.76.

**Comment by rainersigwald** [comment]
Figured out the SpecFlow case: https://github.com/SpecFlowOSS/SpecFlow/issues/1912#issuecomment-604462903.

In short, this is an _expected_ behavior of `Assembly.LoadFile` that was sort of worked around before because MSBuild could find dependencies in `AssemblyLoadContext.Default`.

**Comment by AArnott** [comment]
@rainersigwald It turns out it _isn't_ solved by coverlet.msbuild 2.8.1. This PR is blocked in updating to .NET SDK 3.1.201 because of this same break, and updating coverlet didn't fix it. So I'm still blocked.

https://github.com/AArnott/Nerdbank.Streams/pull/180/files

**Comment by rainersigwald** [comment]
@AArnott sorry it took me a while to get to this, but I don't see anything that looks like an MSBuild task failure in that PR. Can you point me to what you think is failing?

**Comment by AArnott** [comment]
Quite right. I forgot in that PR that updating to coverlet.msbuild 2.8.1 also changes the filenames of the coverage files generated, so there's more to adapting to the task loader change than just updating the package reference.

**Comment by rainersigwald** [comment]
Closing: all of the known active-development tasks that had problems have been fixed in new releases.

**Comment by marcpopMSFT** [comment]
For gitversion, recent exceptions customers have been facing have been the below: Adding a comment to help with customer searches.
Error Exception in initialization: System.IO.FileNotFoundException: Could not load file or assembly ‘System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51’ or one of its dependencies. The system cannot find the file specified.
